# Generated by Django 4.1.3 on 2023-02-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigbasketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_img',
            new_name='ID_proof',
        ),
    ]
